### ISSUE TITLE
Do you plan to open-source a web app used for playback?

### ISSUE THREAD

**Issue by vgrigoruk** [domderen/playwright-session#1]
I'd like to try this on a project, however our company policy doesn't allow to use a 3rd-party service for playback (https://playwright-session.hotdata.co/). Are there any plans to open-source a web app @domderen ?

**Comment by domderen** [comment]
Hey Vitalii, yes I do plan to open-source it, but I was planning to spend some more time on it before open sourcing it. It's quite scrappy at the moment :) 

Out or curiosity, can I ask what is the problem with the hosted version? Playback works fully locally, so you should be able to open the link and use the app even if you turn off the network connection.

**Comment by alex-popov-tech** [comment]
@domderen hey, any updates on that?

**Comment by domderen** [comment]
Not yet, but hopefully soon :)

**Comment by lg** [comment]
hi, i'm also interested. even if it's in a broken beta form. just concerned about session privacy if i'm uploading things to the internet...

**Comment by ashwinmenkudle** [comment]
+1

**Comment by domderen** [comment]
Hey everyone, please take a look at the response in the other issue: https://github.com/domderen/playwright-session/issues/2#issuecomment-757996432
